// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package database

import (
	"context"
	"database/sql"
)

// DBTX is an interface for database transaction or connection.
type DBTX interface {
	ExecContext(context.Context, string, ...interface{}) (sql.Result, error)
	PrepareContext(context.Context, string) (*sql.Stmt, error)
	QueryContext(context.Context, string, ...interface{}) (*sql.Rows, error)
	QueryRowContext(context.Context, string, ...interface{}) *sql.Row
}

// New creates a new Queries object with the given DBTX.
func New(db DBTX) *Queries {
	return &Queries{db: db}
}

// Queries holds the database connection and provides methods for executing queries.
type Queries struct {
	db DBTX
}

// WithTx creates a new Queries object with a transaction.
func (q *Queries) WithTx(tx *sql.Tx) *Queries {
	return &Queries{
		db: tx,
	}
}
